Repository sensu/sensu, pull requests merged in 2018-03, with the labels that each got.

#1800 TCP/UDP socket supports enabled option
  lib/sensu/client/process.rb
Labels: Feature, next

#1818 Client socket "enabled" validation and fix
  lib/sensu/client/process.rb
  lib/sensu/daemon.rb
  sensu.gemspec
Labels: in progress

#1819 Sign the Sensu Ruby gem
  certs/sensu.pem
  lib/sensu/daemon.rb
  sensu.gemspec
Labels: ready-for-review

#1820 Create release checklist
  release-checklist.md
Labels: in progress

#1822 Add Redis TLS support
  lib/sensu/daemon.rb
  sensu.gemspec
Labels: ready-for-review

#1823 Do not write empty data to TCP handler socket
  lib/sensu/server/handle.rb
  spec/server/handle_spec.rb
Labels: in progress, ready-for-review

#1824 Don't require client subscriptions for POST /clients
  lib/sensu/api/routes/clients.rb
  spec/api/process_spec.rb
Labels: in progress

#1825 Fixed RabbitMQ DNS resolution exponential backup
  lib/sensu/daemon.rb
  sensu.gemspec
Labels: ready-for-review

#1829 Allow flapping events to be force resolved
  lib/sensu/server/process.rb
  spec/server/process_spec.rb
Labels: ready-for-review
